### ISSUE TITLE
Error while scanning QR code

### ISSUE THREAD

**Issue by only1sham** [Azure-Samples/active-directory-verifiable-credentials#2]
When I scan the QR code from Microsoft Authenticator app, I see the following error - "Invalid activation barcode". Any inputs on how to resolve this would be appreciated.

Also, on a different note, is it possible to configure and run this solution locally without using Azure AD?

Regards,
Sham

**Comment by timcappalli** [comment]
Please provide the decoded QR value.

Azure AD is not required. Any OIDC-compliant OP can be used.

**Comment by only1sham** [comment]
Here's the value for issue QR code - openid://vc/?request_uri=https%3A%2F%2Fbb41ae627b86.ngrok.io%2Fissue-request.jwt%3Fid%3DbTumSi2L4wCaFfkh2A3BHjSvWPyJBpSh

**Comment by timcappalli** [comment]
That looks correct. Are you using Microsoft Authenticator (Android) version 6.2007.5012 or greater?

**Comment by only1sham** [comment]
I' actually setting the host variable with ngrok URL dynamically something like this. So, it keeps changing.

var server = app.listen(port, function () {
    ngrok.connect(port).then(ngrokUrl => {
        host = ngrokUrl
    })
});

I'm trying to scan QR code from iPhone. Is that an issue?

**Comment by timcappalli** [comment]
The preview is only available in the Android version of Authenticator.

**Comment by only1sham** [comment]
@timcappalli - Thank you for your time in responding to this query! That explains why I get that error on my phone.
