### ISSUE TITLE
 Could not retrieve {"keyReference":"#.....","type":"key","remoteKeyReference":"issuerSigningKeyIon...

### ISSUE THREAD

**Issue by ibLaunch** [Azure-Samples/active-directory-verifiable-credentials#30]
Following the steps from here:

https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/issue-verify-verifiable-credentials-your-tenant

and calling this URL:
.../issue-request

But running into following issue:

 Could not retrieve {"keyReference":"#.....","type":"key","remoteKeyReference":"issuerSigningKeyIon-..............d"}. Error: RestError: The policy requires the caller 'appid=53.....f;oid=......;iss=https://sts.windows.net/*.....*/' to use on-behalf-of (OBO) flow. For more information on OBO, please see https://go.microsoft.com/fwlink/?linkid=2152310
 This seems like a key vault access issue, although proper steps were followed. Maybe the error above gives the proper clue.

I removed the values from the URL in the above response.

**Comment by ibLaunch** [comment]
Found Solution here:
https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/126

**Comment by srikanthakshay** [comment]
Following steps from Here:
https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/issue-verify-verifiable-credentials-your-tenant

while try test the  issuer (issue the verifiable credential) , at Add a credential screen -->after sign in to my account, getting below error after
Troubleshooting details If you contact your administrator, send this info to them.
Copy info to clipboard   Copied
Request Id: a6bf36d1-28b5-4be0-91f3-e6bfdb6c4900
Correlation Id: 4af1f2ff-5abe-47c6-b5dc-81fcd0b39928
Timestamp: 2021-06-07T14:11:54Z
Message: AADSTS500113: **No reply address is registered for the application.**
Flag sign-in errors for review: Enable flagging

**Comment by johncra** [comment]
Check you have set the reply URI during the app registration in Azure AD

***@***.***D75BB7.8D32D2E0]

If that is correct, check that the Rules file has a matching URI

"redirect_uri": "vcclient://openid",

Good luck
John
