### ISSUE TITLE
Custom Optional Claim Type

### ISSUE THREAD

**Issue by leordev** [Azure-Samples/active-directory-verifiable-credentials#31]
I followed the main aka.ms/didfordevs guides and everything worked. I went further a little bit by trying to add custom attributes in my Azure AD to issue my Verifiable Credentials with extra info.

I can see that my id token has my custom attribute:
```
{
// ...
  "extn.dateOfBirth": [
    "1990-01-01"
  ],
  "family_name": "Ribeiro",
  "given_name": "Leo",
// ...
}
```

My VCs configs are:

```json
// vc-rules.json
    "mapping": {
          "firstName": { "claim": "given_name" },
          "lastName": { "claim": "family_name" },
          "dateOfBirth": { "claim": "extn.dateOfBirth" },
    }

// vc-display.json
    "claims": {
      "vc.credentialSubject.firstName": {
        "type": "String",
        "label": "First name"
      },
      "vc.credentialSubject.lastName": {
        "type": "String",
        "label": "Last name"
      },
      "vc.credentialSubject.dateOfBirth": {
        "type": "String",
        "label": "Date of Birth"
      },
```

When trying to issue my VC I actually get an error in the Authenticator:
```
Error Code: unableToDecodeToken

Error Details: Error: VCNetworking.DecodingError
code: 0

Showing error page with unableToDecodeToken details:Error: VCNetworking.DecodingError code: 0 CorrelationVector: S1skSkl9S4uEEC0O70mcmw.8
```

I believe the error is because my custom attribute is being returned as an array of string as opposed to a string.

It's a little bit weird because I setup the dateOfBirth claim as a string, but Azure AD returns it as an array, and I found this: https://social.msdn.microsoft.com/Forums/azure/en-US/1d656d13-8893-4387-859e-6786bba8d086/optional-custom-claim-in-jwt-idtoken-appearing-as-array-not-string?forum=WindowsAzureAD

So it seems like it's expected and the suggestion is to handle it that way (according to above thread).

Question is: how can we handle it to make Authenticator work? Do we have a `String[]` type perhaps?

Another question that I have, seeing the documentation it looks like we can only issue attributes from the following inputs:
- OpenID 
- Other VCs
- Self attested
- Static

Is there any way that I can just issue a VC from my server, with the attributes that I know the user has, and add it to Authenticator without going through the OpenID login inside the authenticator? (It seems redundant to me if the user is already logged in my dashboard and I want to issue a VC to him... Do we have any tutorials with this scenario?)

**Comment by timcappalli** [comment]
`$.[extn.dateOfBirth][0]`

**Comment by ibLaunch** [comment]
Hi Leo - were you able to issue your own VC? we have been having issues doing it, other issue opened is ours, Thanks!

**Comment by timcappalli** [comment]
@leordev can you confirm everything works correctly if you remove that one extension claim?

**Comment by leordev** [comment]
@timcappalli you were right. I had removed the `validityInterval` property from my rules and this was causing the `unableToDecodeToken`.

Thanks for the support, everything seems to be working now!
