### ISSUE TITLE
VCNetworking.DecodingError

### ISSUE THREAD

**Issue by mclasson** [Azure-Samples/active-directory-verifiable-credentials#33]
When I try to validate a given credential (successfully stored in wallet) I can see in the backend that Authenticator calls presentation-request.jwt and gets the token. But then it says as below "DecodingError - unableToDecodeToken".

Where can I begin to troubleshoot this?

```
ERRO VerifiableCredential 0 TID=1 79 (fetchFromUrl(url:)) Error: Error: VCNetworking.DecodingError code: 0 Message: Failed to get the presentation request Properties: ["Line": "79", "Message": "Failed to get the presentation request", "Function": "fetchFromUrl(url:)", "CorrelationVector": "jvgvxzaoTiygyTOkIv/Sdw.0", "File": "/Users/runner/work/1/s/PhoneFactor/VerifiableCredentialWallet/VerifiableCredentialWallet/ViewModel/RequestProcessorViewModel.swift", "Error": "Error: VCNetworking.DecodingError code: 0"]
2021-05-18 11:40:35.320 INFO VerifiableCredential 0 TID=1 141 (stopTrackCurrentMeasuredEvent()) DIDPresentationRequest properties: ["HasFailed": "true", "CorrelationVector": "jvgvxzaoTiygyTOkIv/Sdw.0", "DIDFirstTimeOnBoarding": "false", "DIDSource": "QRScanner"]
2021-05-18 11:40:35.322 VERB VerifiableCredential 0 TID=1 266 (navigateUsing(navigationBlock:)) navigateUsing: view had not appeared CorrelationVector: jvgvxzaoTiygyTOkIv/Sdw.0
2021-05-18 11:40:35.449 VERB VerifiableCredential 0 TID=1 90 (configure()) Showing error page with unableToDecodeToken details:Error: VCNetworking.DecodingError code: 0 CorrelationVector: jvgvxzaoTiygyTOkIv/Sdw.0
```

**Comment by backbone2k** [comment]
I am getting the same error in the Authenticator App (iOS). I cannot not add the VC to my wallet.

**Comment by mclasson** [comment]
@backbone2k My error here was that I made credentialType an array twice. once in
`const credentialType = ['sdfsdf'];`

and then again in
```
input_descriptors: [
        {
          id: "expert",
          schema: {
            uri: [credentialType],
          },
```

**Comment by backbone2k** [comment]
Hi @mclasson,

I have not changed the input_descriptors array. Only modified the credntialType const. I am not sure about the documentation when it comes to the Azure KeyVault. Have you made any changes to the didconfig.json at all ot the the variables: kvVaultUri, kvSigningId and kvRemoteSigningKeyId? The documentation explains to note down certain information from the newly created KeyVault but these are not used in the following parts....

I am really not getting what I did wrong :-(

**Comment by mclasson** [comment]
@backbone2k Yes, they are all my values. You get them from this page
https://portal.azure.com/#blade/Microsoft_AAD_DecentralizedIdentity/InitialMenuBlade/issuerSettingsBlade
copy the did and paste it here https://identity.foundation/ion/explorer/ to get the kvSigningKeyId.
The azClientId and azClientSecret you got from where you did the AppRegistration

**Comment by backbone2k** [comment]
@mclasson Ah ok - but the azClientId and Secret are the second Tutorial / Part. I got stucked yesterday in the first example where you still use the MS B2C demo environment (https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/enable-your-tenant-verifiable-credentials) - But maybe I just toss this one and head over to the second part :-)

**Comment by johncra** [comment]
I have just published a blog which may help. https://www.xtseminars.co.uk/post/issuing-your-own-dids-vcs-with-azure-ad

**Comment by backbone2k** [comment]
Hi @johncra,

thank you very much for your awesome resources on DID/VC. I started over from scratch, cloned the repo and made the modifications to the issuer app.js file - same issue.  I think your information on "waiting" for the VC instance was the point I was missing. I think I was unpatient... Now it is working ;)

--
Christian

**Comment by johncra** [comment]
I am glad it’s working!

**Comment by iBoonz** [comment]
Thanks @mclasson , same mistake here :). You saved my alot of hours :)
