### ISSUE TITLE
Can't run the active-directory-verifiable-credentials sample app on cloud without ngrok

### ISSUE THREAD

**Issue by jasoncys** [Azure-Samples/active-directory-verifiable-credentials#35]
Hi, I tried to run the sample app (both issuer and verifier) on my cloud Ubuntu instance (http://mydomain). I can access the Issuance and Verification page through **http://mydomain:8081** and **http://mydomain:8082** respectively (both Issuance and Verification are run in Docker container).

However, I can never get through to the "Sign In" screen in Authenticator after scanning the QR code for Issuance. I have to start "ngrok" to make it work. What do I need to do in order to make it work on my cloud Ubuntu instance without using "ngrok"?  Make it "**https://mydomain:8081**" instead of "**http://mydomain:8081**"?  If so, how?

Thanks for the help.

Cheers,
Jason

**Comment by mahoekst** [comment]
When you create the request the QR code points to that request. Authenticator needs to be able to download the request. The request itself is not encoded in the QR code (thats too big) the QR code is a pointer to the request. Authenticator needs to download that request from an SSL address it can reach and trust. NGROK is just a useful tool to create that tunnel. If you can configure your environment and mobile phone to accept the SSL certs and authenticator can connect to your service that should work too
