### ISSUE TITLE
Can't find generate.js file to generate personal DID

### ISSUE THREAD

**Issue by annabandicoot** [Azure-Samples/active-directory-verifiable-credentials#36]
Run node ./generate.js to generate a new DID for  website and create keys in your Key Vault mentioned here: https://github.com/Azure-Samples/active-directory-verifiable-credentials/tree/main/verifier

**Comment by jasoncys** [comment]
I started from here: https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/issue-verify-verifiable-credentials-your-tenant and it works fine.  Hope it helps.



> Run node ./generate.js to generate a new DID for website and create keys in your Key Vault mentioned here: https://github.com/Azure-Samples/active-directory-verifiable-credentials/tree/main/verifier

**Comment by davehorsfall** [comment]
I had this issue last week when I started with this repo. I discovered that 'generate.js' was [removed some months ago](https://github.com/Azure-Samples/active-directory-verifiable-credentials/commit/6a51d59230ee1204a17a0f26f77a1243443d49eb) because it is no longer needed. I just skipped that step and the implementation still works ok.

**Comment by annabandicoot** [comment]
@jasoncys yes i went to that doc as well, but unfortunately when i try to verify credentials it look s like it is not recognizing my AAD and the claims ( name and last name) returned as undefined :( i though i have to generate new keys with generate.js for a new DID... Do you use Microsoft authenticatior as wallet or your costume wallet?

**Comment by annabandicoot** [comment]
> I had this issue last week when I started with this repo. I discovered that 'generate.js' was [removed some months ago](https://github.com/Azure-Samples/active-directory-verifiable-credentials/commit/6a51d59230ee1204a17a0f26f77a1243443d49eb) because it is no longer needed. I just skipped that step and the implementation still works ok.

thank you!

**Comment by mahoekst** [comment]
Sorry, correct, no need for generate.js anymore, we are using the DID which is created when you setup the AAD VC Service.
