### ISSUE TITLE
AADSTS500113: No reply address is registered for the application.

### ISSUE THREAD

**Issue by srikanthakshay** [Azure-Samples/active-directory-verifiable-credentials#37]
Following steps from Here:
https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/issue-verify-verifiable-credentials-your-tenant

while try test the issuer (issue the verifiable credential) , at Add a credential screen -->after sign in to my account and after accept the consent, getting below error after
Troubleshooting details If you contact your administrator, send this info to them.
Copy info to clipboard Copied
Request Id: a6bf36d1-28b5-4be0-91f3-e6bfdb6c4900
Correlation Id: 4af1f2ff-5abe-47c6-b5dc-81fcd0b39928
Timestamp: 2021-06-07T14:11:54Z
Message: AADSTS500113: No reply address is registered for the application.
Flag sign-in errors for review: Enable flagged

I haven't set the reply URI during the app registration in Azure AD, can you please suggest

**Comment by johncra** [comment]
Just set it to: vcclient://openid

Take a look at my blog if you want more details: https://www.xtseminars.co.uk/post/issuing-your-own-dids-vcs-with-azure-ad

From: srikanthakshay ***@***.***>
Sent: 07 June 2021 16:42
To: Azure-Samples/active-directory-verifiable-credentials ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure-Samples/active-directory-verifiable-credentials] AADSTS500113: No reply address is registered for the application. (#37)


Following steps from Here:
https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/issue-verify-verifiable-credentials-your-tenant

while try test the issuer (issue the verifiable credential) , at Add a credential screen -->after sign in to my account and after accept the consent, getting below error after
Troubleshooting details If you contact your administrator, send this info to them.
Copy info to clipboard Copied
Request Id: a6bf36d1-28b5-4be0-91f3-e6bfdb6c4900
Correlation Id: 4af1f2ff-5abe-47c6-b5dc-81fcd0b39928
Timestamp: 2021-06-07T14:11:54Z
Message: AADSTS500113: No reply address is registered for the application.
Flag sign-in errors for review: Enable flagged

I haven't set the reply URI during the app registration in Azure AD, can you please suggest
