### ISSUE TITLE
Error with issuer sample - missing nonce

### ISSUE THREAD

**Issue by John-Garland** [Azure-Samples/active-directory-verifiable-credentials#40]
Authenticator returns an error when scanning the Issuer-provided QR code. 

**Error Code:SdkException**
Error Details: Unhandled ExceptionField 'nonce' is required, but it was missing.

A temporary workaround is to use the Verifier sample directly, and take advantage of the fact that it is configured to allow issuance.

It does appear that this is addressed in the Verifier project RequestorBuilder, where useNonce and useState calls are included, but similar calls are not present in the Issuer project.

**Comment by mahoekst** [comment]
Thanks, an update from Authenticator on Android broke the sample. We are working on an update.

**Comment by mahoekst** [comment]
Fixed, we added state and nonce to the requistbuilder.
