### ISSUE TITLE
SignUpVCorSignin.xml has validation errors when uploading as custom policy

### ISSUE THREAD

**Issue by mistokes-ppr** [Azure-Samples/active-directory-verifiable-credentials#52]
When uploading SignUpVCorSignin.xml policy, Azure Identity Experience Framework raises a number of errors
* the BasePolicy PolicyId appears to B2C_1A_VC_TrustFrameworkExtensions instead of B2C_1A_TrustFrameworkExtensionsVC
* the Orchestration Steps are 1, 2, 7, 8, 9 instead of 1, 2, 3, 4, 5
* finally after fixing the above, I get the following error
*
Validation failed: 1 validation error(s) found in policy "B2C_1C_VC_ISSUEVC" of tenant <snipped out my tenant name>. User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant <snipped out my tenant name> has step 3 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.

**Comment by cljung** [comment]
@mistokes-ppr I see the problem and will fix this. Thank you for reporting the issue

**Comment by cljung** [comment]
Policy updated
