### ISSUE TITLE
Unhandled ExceptionField 'exp' is required, but it was missing.

### ISSUE THREAD

**Issue by AmitavaHazra** [Azure-Samples/active-directory-verifiable-credentials#55]
Reference Doc:
https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-verifier
 I am using sample code,
git clone git@github.com:Azure-Samples/active-directory-verifiable-credentials-dotnet.git

Here, after setting up required configuration it is generating QR code and once successfully scanned it asked for manual code.
Post this once I click "Add" in authenticator app it is throwing error instead of credential added success message.
**Error message in authenticator app:**
Unhandled ExceptionField 'exp' is required, but it was missing.

Please help and advise.

**Comment by rogulati** [comment]
As per our discussion, this is working now for you. You need to have validityinterval and VC type specified in the Rules file. I will mark this as closed as it's working for you now.
