### ISSUE TITLE
Verified ID B2C Custom policy sample upload errors

### ISSUE THREAD

**Issue by jasonfritts** [Azure-Samples/active-directory-verifiable-credentials#62]
When uploading the B2C example policies, all policies are succesfull except for the following

https://github.com/Azure-Samples/active-directory-verifiable-credentials/blob/main/B2C/policies/SignupOrSigninVCQ.xml

`Validation failed: 2 validation error(s) found in policy "B2C_1A_VC_SUSIQ" of tenant "XXXXXX.onmicrosoft.com".User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "XXXXXX.onmicrosoft.com" has step 7 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "XXXXXX.onmicrosoft.com" has step 8 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "XXXXXX.onmicrosoft.com" has step 7 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susiq" of tenant "XXXXXX.onmicrosoft.com" has step 8 with 2 claims exch...`

https://github.com/Azure-Samples/active-directory-verifiable-credentials/blob/main/B2C/policies/SignUpVCOrSignin.xml

`Validation failed: 2 validation error(s) found in policy "B2C_1A_VC_SUSI_ISSUEVC" of tenant "XXXXXX".User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "XXXXXX" has step 7 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "XXXXXX" has step 8 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "XXXXXX.onmicrosoft.com" has step 7 with 2 claims exchanges. It must be preceded by a claims provider selection in order to determine which claims exchange can be used.User journey "SignUpOrSignIn" in policy "B2C_1A_VC_susi_issuevc" of tenant "XXXXXXt...`

Are there steps missing that would fix these errors?  The other samples were updated \ uploaded without issue.

**Comment by cljung** [comment]
@jasonfritts - investigating

**Comment by cljung** [comment]
The VC+B2C custom policies works with the [SocialAndLocalAccounts](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/main/SocialAndLocalAccounts) base policies.
