### ISSUE TITLE
Presentation request for a subset or a single attribute

### ISSUE THREAD

**Issue by Riff451** [Azure-Samples/active-directory-verifiable-credentials#7]
Hello, I couldn't find an example so I'm asking here. 
Is it possible with the RequestorBuilder to create a request containing just a subset of the attributes defined in the credential type? In the example below just the credential type is defined.
If it's possible is it also possible to remove the credential type from the request and just ask for some attribute names?

Thank you very much.

https://github.com/Azure-Samples/active-directory-verifiable-credentials/blob/84cb07a7803e7356006c5d4fe41b9a7cf3556d32/verifier/app.js#L98

**Comment by dstrockis** [comment]
Hi @Riff451, not at this time. This is something on our roadmap, but not currently supported.
